spring:
  config:
    import: application-secret.yml

  datasource:
    url: jdbc:postgresql://${secret.db.host}:${secret.db.port}/${secret.db.name}
    username: ${secret.db.username}
    password: ${secret.db.password}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000        # ?? ??? ?? ?? ??: 10?
      max-lifetime: 15000        # ?? ??? ?? ??: 15? (10~20? ??? ??)
      connection-timeout: 3000   # ??? ?? ?? ?? ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
logging:
  level:
    org.hibernate.SQL: debug
